name: Fly Deploy
on: 
  push:
    branches:
      - release
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy -e GIT_SHA-$(git rev-parse --short HEAD) -e GIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')"
